### ISSUE TITLE
Removing borders/titlebar

### ISSUE THREAD

**Issue by alexwhitman** [skx/kpie#20]
Would it be possible to add the equivalent of devilspie's `undecorate` action to remove the window borders and title bar?

**Comment by skx** [comment]
All the window operations are carried out via `libwnck`, and so sadly I think that isn't going to be an option.

Looking over the API reference for things that can be done with "windows" I find a bunch of things:

* https://developer.gnome.org/libwnck/stable/WnckWindow.html

But the only reference to "decorations" is in regard to getting the dimensions of the window, I don't see anything obvious for toggling, or getting/setting the state of the decorations.  I suspect this is done at the window-manager level, rather than at the program.

**Comment by skx** [comment]
Scratch that - I've made it work.  Bear with me.

**Comment by skx** [comment]
Sample usage in the commit-message:

* https://github.com/skx/kpie/commit/79b368975a3a20c24937635d85814adbe7797ad6

Tested on metacity (GNOME).

**Comment by alexwhitman** [comment]
Thanks, wasn't expecting it to get done so quickly!  Will the change get pushed to a new version in your repo (https://packages.steve.org.uk/kpie/) ?

**Comment by skx** [comment]
Just lucky timing, yes I'll sort out a new package in the next half-hour or so.

**Comment by skx** [comment]
Packages uploaded for stretch, jessie & wheezy releases of Debian.

(Will probably stop updating wheezy in the future, it is old enough..)

**Comment by alexwhitman** [comment]
Thanks.  I'm actually using Ubuntu 18.04 but the Stretch package works fine.
